[package]
name = "advent-of-code-24"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
