[package]
name = "advent_of_code_24"
version = "0.1.0"
edition = "2021"

[lib]
name = "day_1"
path = "src/day-1.rs"

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
